services:
  nginx:
    image: nginx
    ports:
      - "8080:8080"
      - "8081:8081"
      - "2525:2525"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    hostname: nginx

  # backends:
  ghost:
    image: ghost
    # ports:
    #   - "2368:2368"
    environment:
      NODE_ENV: development
      url: http://localhost:8080
  email:
    image: mailhog/mailhog
    # ports:
    #   - "8025:8025"
    #   # - "1025:1025"
  hello:
    image: hashicorp/http-echo
    command: ["-text", "Hello!"]
    # ports:
    #   - "5678:5678"
