services:
  nginx:
    image: nginx # 1.25.3/mainline/latest, stable
    ports:
      - "80:80"
      # - "8080:8080" # other nginx ports
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/out



## Default path where nginx expect config file is /etc/nginx/nginx.conf
##Mapped 2 Volumes 
##1. Angular Dist Folder to Root Folder
##2. Mapped Config file